import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { AiOutlineArrowUp } from "react-icons/ai";
import Footer from "../layouts/Footer";
import Header from "../layouts/Header";
import Main from "../layouts/Main";
import { ProductItemProps } from "../modules/types";

export const getStaticProps = async () => {
  const res = await fetch(
    "https://630356189eb72a839d7e219b.mockapi.io/razzi13/razzi-products"
  );
  const products = await res.json();

  return {
    props: { products },
  };
};

const goToTop = () => {
  window.scrollTo({
      top: 0,
      behavior: "smooth",
  });
};

const Home: NextPage<{ products: ProductItemProps[] }> = ({ products }) => {
  const [scrollTop, setScrollTop] = useState(false);

  function setScrollToTop() {
    if (window.scrollY >= 620) {
      setScrollTop(true);
    } else {
      setScrollTop(false);
    }
  }

  useEffect(() => {
    window.addEventListener("scroll", setScrollToTop);
  }, []);

  return (
    <div className="">
      <Head>
        <title>Razzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main products={products} />
      <div className={"scroll-to-top" + (scrollTop ? " show" : "")}>
        <div className="scroll-top-wrapper" onClick={goToTop}>
          <AiOutlineArrowUp className="scroll-top-icon" />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Home;
